language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.1"
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec spec
addons:
  code_climate:
    repo_token: 203e7217f95eb57beb64e1c1fd42ac3a379c0f388561387221f0af9799d249f4 